In [1]:
from sklearn.feature_selection import *
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2 as chi2
from scipy.stats import chi2 as chi2stat

from sklearn.feature_selection import mutual_info_classif

In [2]:
X = np.random.rand(5, 10)
y = [0, 1, 2, 0, 1]
print(X)

[[0.36424599 0.27351265 0.12874903 0.95425464 0.32952595 0.75435415
  0.66933908 0.03174379 0.77220692 0.01123767]
 [0.37280301 0.64108256 0.83256869 0.41532676 0.90632237 0.82972105
  0.35280166 0.94356188 0.21686124 0.74150063]
 [0.70829568 0.98498792 0.16714144 0.96159789 0.03730433 0.86766377
  0.73057352 0.46873553 0.22551529 0.52464614]
 [0.10331876 0.49930744 0.52421855 0.05714434 0.57951798 0.15571467
  0.1252312  0.85219787 0.1252585  0.55772454]
 [0.75998274 0.57132381 0.39305731 0.82914266 0.60083872 0.75723174
  0.19150929 0.15422304 0.28971407 0.81032391]]


In [7]:
mutual_info = mutual_info_classif(X, y)
print(mutual_info > 0)

[ True False False False  True  True False False  True  True]


In [3]:
np.where(chi2(X, y)[1] > .9)[0]

array([7, 8])

In [13]:
chi2stat.ppf(q = chi2(X, y)[1][0], df = 1)

2.5039337170541613

In [9]:
ch2 = SelectKBest(chi2, k=2)
X_new = ch2.fit_transform(X, y)
print(np.where(ch2.get_support())[0])
print(ch2.get_support())

[2 4]
[False False  True False  True False False False False False]


In [3]:
chi2(X, y)

(array([0.05004772, 0.13125046, 1.13347549, 0.24609666, 0.13921883,
        0.50074623, 0.31446741, 0.26074164, 0.04214027, 0.37329807]),
 array([0.97528664, 0.93648176, 0.56737334, 0.88422093, 0.93275807,
        0.77851025, 0.85450433, 0.87776987, 0.97915029, 0.82973489]))

In [1]:
from gensim.corpora import Dictionary

In [4]:
dictionary = Dictionary()

In [5]:
dictionary.add_documents(['I am Iron Man'.split()])

In [12]:
len(dictionary)

4

In [14]:
dictionary.token2id['Iron']

1

In [21]:
summary = dictionary.doc2idx('I am Iron Groot'.split())

In [22]:
summary

[0, 3, 1, -1]

In [20]:
for j in range(len(summary)):
    print(summary[j])

0
3
1
1
2


In [23]:
import numpy as np

In [24]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
sum(a[0])

6

In [27]:
a[0]

array([1, 2, 3])

In [29]:
a[:][2]

array([7, 8, 9])

In [30]:
a = np.array([1, 2, 3, 4, 5])

In [31]:
np.sum(a) - a

array([14, 13, 12, 11, 10])

In [62]:
a[:][0]

[1, 0, 1, 0, 1]

In [64]:
np.unique(a[, 0])

SyntaxError: invalid syntax (<ipython-input-64-7b52af9e6506>, line 1)

In [8]:
a = [
    [1, 0, 1, 0, 1],
    [0, 2, 1 ,0, 2],
    [1, 1, 1, 0, 0],
    [2, 0, 0, 0, 2],
    [3, 0, 0, 0, 1]
]
X = np.array(a)
y = np.array([0, 1, 0, 2, 2])

In [14]:
print(X)
print(np.unique(X[:, 1]))
print(y)

[[1 0 1 0 1]
 [0 2 1 0 2]
 [1 1 1 0 0]
 [2 0 0 0 2]
 [3 0 0 0 1]]
[0 1 2]
[0 1 0 2 2]


In [36]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [50]:
selector = SelectKBest(chi2, k=2)
X_new = selector.fit_transform(X, y)

In [51]:
indices_selected = selector.get_support(indices=True)
print(indices_selected)

[0 1]


In [42]:
X_new

array([[1, 0, 1, 1],
       [0, 2, 1, 2],
       [1, 1, 1, 0],
       [2, 0, 0, 2],
       [3, 0, 0, 1]])

In [43]:
chi2(X, y)

(array([3.35714286, 4.5       , 2.        ,        nan, 1.5       ]),
 array([0.18664041, 0.10539922, 0.36787944,        nan, 0.47236655]))

In [44]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [45]:
chi2_selector = SelectKBest(chi2, k=2)
X_kbest = chi2_selector.fit_transform(X, y, )

In [46]:
X_kbest

array([[1, 0],
       [0, 2],
       [1, 1],
       [2, 0],
       [3, 0]])

In [52]:
from sklearn.feature_selection import mutual_info_classif

In [53]:
mutual_info_classif(X, y)

array([0.45833333, 0.20833333, 0.83333333, 0.        , 0.33333333])

In [18]:
X

array([[0.52187247, 0.75522841, 0.33942899, 0.40470493, 0.59004344,
        0.61869713, 0.60995582, 0.68897856, 0.07097596, 0.10109774],
       [0.87527513, 0.552761  , 0.61707899, 0.47579143, 0.17960087,
        0.96564765, 0.05910339, 0.6920776 , 0.35877876, 0.87929619],
       [0.11072128, 0.51887942, 0.67093327, 0.49461834, 0.76435154,
        0.60316192, 0.31280539, 0.74540373, 0.95808466, 0.35870002],
       [0.13522021, 0.18173736, 0.43085842, 0.95686966, 0.26848409,
        0.01967452, 0.47747683, 0.18426456, 0.67329628, 0.84951126],
       [0.04361059, 0.66454829, 0.29100337, 0.09551014, 0.97651454,
        0.25853529, 0.05449445, 0.45468796, 0.13215465, 0.73300973]])

In [68]:
np.unique(X[:, 0])

array([0, 1, 2, 3])

In [19]:
X = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 6, 5], [1, 4, 4, 5, 5]])

In [22]:
len(np.unique(X))

6