In [1]:
# Import pandas
import pandas as pd
import numpy as np
from gensim.corpora import Dictionary
from sklearn.model_selection import train_test_split

In [2]:
# Assign spreadsheet filename to `file`
file = 'Eclipse_4sourcev1.xls'
# Load spreadsheet
xl = pd.ExcelFile(file)
# Load a sheet into a DataFrame by name: df1
df = xl.parse('total')

In [3]:
class NaiveBayesClassifer:
    def __init__(self):
        self.name = 'Naive Bayes Classifier'
    
    def train (self, X_train, y_train, number_of_unique_words = 100000):
        self.prior = np.zeros(5)
        labels = list(y_train)
        
        for i in range(5):
            self.prior[i] = labels.count(i)/len(labels)
        print(self.prior)
        self.mle_summary = np.zeros((number_of_unique_words, 5))
        self.wordCount_summary = np.zeros(5)
        
        summaries = list(X_train.loc[:,'summary'])

        self.dictionary = Dictionary()

        for summary in summaries:
            self.dictionary.add_documents([summary.split()])

        for i in range(len(summaries)):
            summaries[i] = self.dictionary.doc2idx(summaries[i].split())
        
        for i in range(len(summaries)):
            summary = summaries[i]
            for word in summary:
                self.mle_summary[word][labels[i]] += 1 
                self.wordCount_summary[labels[i]] += 1
        
        for i in range(number_of_unique_words):
            for j in range(5):
                self.mle_summary[i][j] += 1
                self.mle_summary[i][j] /= (self.wordCount_summary[j])
        
        self.mle_desc = np.zeros((number_of_unique_words, 5))
        self.wordCount_desc = np.zeros(5)
        
        descriptions = list(X_train.loc[:,'description'])
    
        for description in descriptions:
            self.dictionary.add_documents([description.split()])

        for i in range(len(descriptions)):
            descriptions[i] = self.dictionary.doc2idx(descriptions[i].split())
        
        
        for i in range(len(descriptions)):
            description = descriptions[i]
            for word in description:
                '''
                if (i==0):
                    print(word, self.wordCount_desc[word])
                '''
                self.mle_desc[word][labels[i]] += 1
                self.wordCount_desc[labels[i]] += 1
        
        for i in range(number_of_unique_words):
            for j in range(5):
                self.mle_desc[i][j] += 1
                self.mle_desc[i][j] /= self.wordCount_desc[labels[j]]
        
        pass
    
    def predict (self, X_test):
        y_test = np.ones((X_test.shape[0], 5))
        for i in range(X_test.shape[0]):
            for j in range(5):
                y_test[i][j] = (self.prior[j])
        
        summaries = list(X_test.loc[:,'summary'])
        for summary in summaries:
            self.dictionary.add_documents([summary.split()])
        for i in range(len(summaries)):
            summaries[i] = self.dictionary.doc2idx(summaries[i].split())
        
        descriptions = list(X_test.loc[:,'description'])
        for description in descriptions:
            self.dictionary.add_documents([description.split()])
        for i in range(len(descriptions)):
            descriptions[i] = self.dictionary.doc2idx(descriptions[i].split())
        
        for i in range(X_test.shape[0]):
            for j in range(5):
                log_sum_summary = 0
                log_sum_desc = 0
                for word in summaries[i]:
                    if word != -1 and self.mle_summary[word][j] != 0:
                        log_sum_summary += np.log(self.mle_summary[word][j])
                for word in descriptions[i]:
                    if word != -1 and self.mle_desc[word][j] != 0:
                        log_sum_desc += np.log(self.mle_desc[word][j])
                
                y_test[i][j] = np.log(y_test[i][j])
                y_test[i][j] += ((log_sum_summary) + (log_sum_desc))
                
                ''' + (log_sum_desc) '''
        #print(y_test)
        ret_val = np.zeros(len(y_test))
        
        cnt = 0
        for i in range(X_test.shape[0]):
            mx = 0
            mxindex = -1
            for j in range(5):
                if y_test[i][j] != 0:
                    if mxindex == -1 or y_test[i][j] > mx:
                        mxindex = j
                        mx = y_test[i][j]
            if mxindex == -1:
                cnt += 1
                mxindex = cnt % 5
            ret_val[i] = mxindex
        ret_val =  [int(round(x)) for x in ret_val] 
        print('Number of random classifications: ',cnt)
        return list(ret_val)

In [4]:

# create training and testing vars
y = df.loc[:,'label'] - 1
X = df.loc[:, 'summary':'component']

In [5]:
naiveBayesClassifier = NaiveBayesClassifer()
f1_scores_list = []

In [6]:
f1_scores = np.zeros((10, 5))
for i in range(1,11):
    split_point = (len(X)/11) * i
    naiveBayesClassifier.train(X_train = X.loc[0:split_point,], y_train = y.loc[0:split_point, ])
    y_test = naiveBayesClassifier.predict(X_test = X.loc[split_point:, ])
    
    
    y_label = list(y.loc[split_point:, ])
    
    #print(y_test, y_label)
    #print((y_test == y_label).count(True) / len(y_test))
    
    
    true_positive = np.zeros(5)
    
    false_positive = np.zeros(5)
    false_negative = np.zeros(5)
    
    for j in range(len(y_test)):
        if (y_test[j] == y_label[j]):
            true_positive[y_test[j]] += 1
        else:
            false_positive[y_test[j]] += 1
            false_negative[y_label[j]] += 1
    
    precision = np.zeros(5)
    recall = np.zeros(5)
    for j in range(5):
        precision[j] = true_positive[j] / (true_positive[j] + false_positive[j])
        recall[j] = true_positive[j] / (true_positive[j] + false_negative[j])
    
    for j in range(5):
        f1_scores[i-1][j] = (2 * (precision[j] * recall[j])) / (precision[j] + recall[j]) 
    print('Count: Train vs Test')
    print(y_test.count(0), y_label.count(0))
    print(y_test.count(1), y_label.count(1))
    print(y_test.count(2), y_label.count(2))
    print(y_test.count(3), y_label.count(3))
    print(y_test.count(4), y_label.count(4))
    
    print('F-measure after ', i, 'th iteration: ', f1_scores[i-1])
    f1_scores_list.append(f1_scores)
    pass
    

[0.04769001 0.3681073  0.33532042 0.17585693 0.07302534]
Number of random classifications:  0
Count: Train vs Test
318 698
4358 1191
1980 2756
35 1268
11 789
F-measure after  1 th iteration:  [0.08267717 0.31140746 0.31714527 0.02762855 0.01      ]
[0.05070843 0.31618195 0.35868755 0.18866518 0.0857569 ]
Number of random classifications:  0
Count: Train vs Test
169 662
2471 1014
3341 2500
40 1133
11 723
F-measure after  2 th iteration:  [0.06738869 0.27317073 0.46841294 0.02046036 0.01362398]
[0.0512183  0.27747389 0.37493784 0.18896072 0.10740925]
Number of random classifications:  0
Count: Train vs Test
79 627
541 880
4699 2227
30 1006
13 622
F-measure after  3 th iteration:  [0.0509915  0.15904293 0.56887092 0.02316602 0.01889764]
[0.05033557 0.24794929 0.39932886 0.19686801 0.10551827]
Number of random classifications:  0
Count: Train vs Test
50 595
115 773
4497 1910
16 858
13 555
F-measure after  4 th iteration:  [0.04031008 0.05405405 0.57686905 0.00457666 0.02816901]
[0.0528043 

/home/immuntasir/.local/lib/python3.5/site-packages/ipykernel_launcher.py:33: RuntimeWarning: invalid value encountered in double_scalars


Number of random classifications:  0
Count: Train vs Test
4 337
43 320
1948 822
7 318
8 213
F-measure after  8 th iteration:  [0.0058651  0.03856749 0.57545126        nan 0.0361991 ]
[0.07541853 0.20039781 0.40261893 0.20023206 0.12133267]
Number of random classifications:  0
Count: Train vs Test
3 275
30 229
1300 552
2 178
5 106
F-measure after  9 th iteration:  [0.01438849 0.04633205 0.57991361        nan 0.03603604]
[0.08294793 0.19528569 0.40563927 0.19558407 0.12054304]
Number of random classifications:  0
Count: Train vs Test
0 174
11 129
656 262
0 75
3 30
F-measure after  10 th iteration:  [       nan 0.04285714 0.5664488         nan 0.06060606]


/home/immuntasir/.local/lib/python3.5/site-packages/ipykernel_launcher.py:29: RuntimeWarning: invalid value encountered in double_scalars


In [8]:
np.log([0.04769001, 0.3681073,  0.33532042, 0.17585693, 0.07302534])

array([-3.04303334, -0.99938081, -1.09266873, -1.73808451, -2.61694877])

In [9]:
from gensim.corpora import Dictionary

texts = [['human', 'interface', 'computer']]
dct = Dictionary(texts)  # initialize a Dictionary
dct.add_documents([["cat", "say", "meow"], ["dog"]])

In [24]:
for key in dct.keys():
    print(dct[key])

interface
computer
say
meow
dog
human
cat
